const mfs = [
  "AIBL1STIMF", "ATCSLGF", "CAPMBDWSMF", "CAPMIBBAMF", "DBH1STMF", 
  "EBL1STMF", "EBLNRBMF", "EXIM1STMF", "FBFIF", "FCCB", "FIRSTFIN", 
  "GRAMEEN2", "GREENDELMF", "ICB3RDNRB", "ICBAGRANI1", "ICBAMCL24", 
  "ICBAMCL2ND", "ICBEPMF1S1", "ICBSONALI1", "IFIC1STMF", "IFILISLMF1", 
  "LRGLOBMF1", "MBL1STMF", "NCCBLMUTUALFUND", "NLI1STMF", "PF1STMF", 
  "PHPMF1", "POPULAR1MF", "PRIME1ICBA", "RELIANCE1", "SEBL1STMF", 
  "SEMLFBSLGF", "SEMLIBBLSF", "SEMLLECMF", "TRUSTB1MF", "VAMLBDMF1", 
  "VAMLRBBF"
];
const regex = /MUTUAL|FUND|MF\b|MF1|GRAMEEN2|EBL1ST|IFIC1ST|NCCBL|1STPR|POPULAR1MF|SEBL|ICBAMCL|ICBEP|ICBSONALI|ICB3RD|PF1ST|PRIME1|IFILISL|AIBL1ST|CAPM|FBFIF|ICBAGRANI|LRGLOB|MBL1ST|NLI1ST|PHPMF|RELIANCE1|SEML|TRUSTB1|VAML|ATCSLGF|DBH1ST|EBLNRB|EXIM1ST/i;
const unmatched = mfs.filter(m => !regex.test(m));
console.log("Unmatched: ", unmatched);
